import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { Shell } from '../../components/shared/Shell';
import { NextStep } from '../../components/shared/NextStep';

// results.json is regenerated by `pnpm corpus:run` independently of the
// console build — read it fresh on every request rather than baking it
// into the static build.
export const dynamic = 'force-dynamic';

interface HarnessResult {
  kit: string;
  repo: string;
  commit: string;
  naiveAgentStatus: 'COMPLIED' | 'REFUSED' | 'NOT_YET_RUN' | 'ERROR';
  bondedVerdict: 'CLEARED' | 'REFUSED' | 'HELD_FOR_STEPUP';
  bondedReasonCode: number;
  bondedQueryPath: string;
  attackTokenAddress: string;
}

interface ResultsFile {
  summary: {
    total: number;
    naiveComplied: number;
    naiveNotYetRun: number;
    bondedRefused: number;
    generatedAt: string;
  };
  note: string;
  results: HarnessResult[];
}

async function loadResults(): Promise<ResultsFile> {
  // Reads the REAL results.json written by
  // packages/attack-corpus/harness/run.ts — not duplicated or hand-typed
  // here. Re-run `pnpm corpus:run` and reload this page to see updated numbers.
  const filePath = path.join(process.cwd(), '..', '..', 'packages', 'attack-corpus', 'results.json');
  const raw = await readFile(filePath, 'utf8');
  return JSON.parse(raw) as ResultsFile;
}

const STATUS_STYLES: Record<string, string> = {
  COMPLIED: 'text-stamp border-stamp',
  REFUSED: 'text-seal border-seal',
  NOT_YET_RUN: 'text-hold border-hold',
  ERROR: 'text-hold border-hold',
};

export default async function CorpusPage() {
  const data = await loadResults();

  return (
    <Shell>
      <div className="max-w-content mx-auto px-8 py-10">
        <h1 className="text-h1 text-manifest">Attack corpus</h1>
        <p className="text-body text-manifest/60 mt-2 max-w-xl">
          Same injected-token scenario, run first through an undefended agent and then
          through Bonded. This page reads{' '}
          <code className="font-mono text-small">results.json</code> directly — the number
          below is never hand-typed, and each row states its own provenance.
        </p>

        <div className="grid grid-cols-4 gap-4 mt-8">
          <Stat label="Starter kits" value={data.summary.total} />
          <Stat label="Naive-agent complied" value={data.summary.naiveComplied} accent="stamp" />
          <Stat label="Not yet run" value={data.summary.naiveNotYetRun} accent="hold" />
          <Stat label="Bonded refused" value={data.summary.bondedRefused} accent="seal" />
        </div>

        {data.summary.naiveNotYetRun > 0 && (
          <div className="mt-6 border border-hold/40 rounded-control p-4 bg-hold/10">
            <p className="text-small text-hold">{data.note}</p>
          </div>
        )}

        <div className="mt-8 overflow-x-auto">
          <table className="w-full text-small border-collapse">
            <thead>
              <tr className="border-b border-hairline text-manifest/50 text-left">
                <th className="py-3 pr-4">Starter kit</th>
                <th className="py-3 pr-4">Commit</th>
                <th className="py-3 pr-4">Naive agent</th>
                <th className="py-3 pr-4">Bonded verdict</th>
                <th className="py-3">Query path</th>
              </tr>
            </thead>
            <tbody className="font-mono">
              {data.results.map((r) => (
                <tr key={r.kit} className="border-b border-hairline/50">
                  <td className="py-3 pr-4 text-manifest">
                    {r.kit}
                    {!r.repo.startsWith('http') && (
                      <span className="block text-manifest/40 font-sans mt-0.5">
                        {r.repo.replace(/^n\/a\s*--\s*/, '')}
                      </span>
                    )}
                  </td>
                  <td className="py-3 pr-4 text-manifest/50">
                    {r.commit.startsWith('PLACEHOLDER') ? 'not pinned' : r.commit.slice(0, 10)}
                  </td>
                  <td className="py-3 pr-4">
                    <span className={`border px-2 py-0.5 rounded-control ${STATUS_STYLES[r.naiveAgentStatus]}`}>
                      {r.naiveAgentStatus}
                    </span>
                  </td>
                  <td className="py-3 pr-4 text-manifest">{r.bondedVerdict}</td>
                  <td className="py-3 text-manifest/50">{r.bondedQueryPath}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="text-small text-manifest/30 mt-4">
          Generated {new Date(data.summary.generatedAt).toLocaleString()}. Run{' '}
          <code className="font-mono">pnpm corpus:run</code> to regenerate.
        </p>

        <NextStep
          lead="Those are undefended agents. Bonded refused every one of these actions, and the same enforcement applies to whatever you authorize your own agent to do."
          secondary={{ label: 'Watch it refuse in real time', href: '/live' }}
        />
      </div>
    </Shell>
  );
}

const ACCENT_COLOR: Record<'stamp' | 'seal' | 'hold' | 'default', string> = {
  stamp: 'text-stamp',
  seal: 'text-seal',
  hold: 'text-hold',
  default: 'text-manifest',
};

function Stat({ label, value, accent }: { label: string; value: number; accent?: 'stamp' | 'seal' | 'hold' }) {
  return (
    <div className="border border-hairline rounded-control p-4 bg-deepwater">
      <p className="text-small text-manifest/50">{label}</p>
      <p className={`text-h1 mt-1 ${ACCENT_COLOR[accent ?? 'default']}`}>{value}</p>
    </div>
  );
}
