import { readFile } from 'node:fs/promises';
import path from 'node:path';

import Link from 'next/link';

import { CountUp } from './CountUp';
import { MeshGradient } from './MeshGradient';

/**
 * Live receipt strip — docs/LANDING_PAGE_SPEC.md §5.5.
 *
 * Async server component. Reads the REAL
 * `packages/attack-corpus/results.json` written by
 * packages/attack-corpus/harness/run.ts — the same file and the same
 * cwd-relative path resolution `app/corpus/page.tsx` uses. Numbers are never
 * hand-typed here.
 *
 * HONESTY CONTRACT (spec §5.5 and §9): `naiveComplied` is currently 0 only
 * because `naiveNotYetRun` is 3 — nothing has been run, so nothing has had the
 * chance to comply. Whenever `naiveNotYetRun > 0` this strip leads with the
 * pending state and explicitly annotates the complied count as "not a result
 * yet", instead of presenting a triumphant "0 complied".
 */

// results.json is regenerated by `pnpm corpus:run` independently of the console
// build — read it fresh on every request rather than baking it into the build.
// Note: route-segment config is only honoured on a route file, so the page that
// renders this strip (app/page.tsx) must carry the same export for it to take
// effect; it is declared here as the component's stated requirement.
export const dynamic = 'force-dynamic';

interface ResultsSummary {
  total: number;
  naiveComplied: number;
  naiveNotYetRun: number;
  bondedRefused: number;
  generatedAt: string;
}

interface ResultsFile {
  summary: ResultsSummary;
  note: string;
}

async function loadSummary(): Promise<ResultsFile> {
  const filePath = path.join(
    process.cwd(),
    '..',
    '..',
    'packages',
    'attack-corpus',
    'results.json',
  );
  const raw = await readFile(filePath, 'utf8');
  return JSON.parse(raw) as ResultsFile;
}

export async function ReceiptCounter({ className = '' }: { className?: string }) {
  const data = await loadSummary();
  const { summary, note } = data;
  const pending = summary.naiveNotYetRun > 0;

  return (
    <section className={`max-w-content mx-auto px-8 ${className}`}>
      <MeshGradient className="rounded-doc border border-hairline">
        <div className="p-8">
          <h2 className="text-h2 text-manifest">The receipt</h2>
          <p className="text-body text-manifest/60 mt-2 prose">
            These four numbers are read straight out of{' '}
            <code className="font-mono text-small">packages/attack-corpus/results.json</code>{' '}
            on every request. None of them is typed into this page.
          </p>

          {pending && (
            <div className="mt-6 rounded-control border border-hold/40 bg-hold/10 p-4">
              <p className="text-small text-hold">
                Corpus run pending — {summary.naiveNotYetRun} of {summary.total} starter
                kits have not been run yet, so the naive-agent column is not a result.{' '}
                <Link href="/corpus" className="underline underline-offset-4">
                  See the receipt live at /corpus
                </Link>
                .
              </p>
              <p className="text-small text-manifest/50 mt-2">{note}</p>
            </div>
          )}

          <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <Stat label="Starter kits" value={summary.total} />
            <Stat
              label="Naive-agent complied"
              value={summary.naiveComplied}
              accent="stamp"
              caveat={pending ? 'not a result yet — nothing has been run' : undefined}
            />
            <Stat
              label="Not yet run"
              value={summary.naiveNotYetRun}
              accent="hold"
            />
            <Stat
              label="Bonded refused"
              value={summary.bondedRefused}
              accent="seal"
              caveat="POLICY_FORBIDDEN_ACTION (reasonCode 3)"
            />
          </div>

          <p className="text-small text-manifest/40 mt-6">
            Generated{' '}
            <span className="font-mono">
              {new Date(summary.generatedAt).toISOString()}
            </span>
            .{' '}
            <Link href="/corpus" className="text-manifest underline underline-offset-4">
              Full table →
            </Link>
          </p>
        </div>
      </MeshGradient>
    </section>
  );
}

const ACCENT: Record<'stamp' | 'seal' | 'hold' | 'default', string> = {
  stamp: 'text-stamp',
  seal: 'text-seal',
  hold: 'text-hold',
  default: 'text-manifest',
};

function Stat({
  label,
  value,
  accent,
  caveat,
}: {
  label: string;
  value: number;
  accent?: 'stamp' | 'seal' | 'hold';
  caveat?: string;
}) {
  return (
    <div className="rounded-control border border-hairline bg-deepwater/70 p-4">
      <p className="text-small text-manifest/50">{label}</p>
      <CountUp
        value={value}
        className={`text-h1 font-mono mt-1 block ${ACCENT[accent ?? 'default']}`}
      />
      {caveat && <p className="text-small text-manifest/40 mt-1">{caveat}</p>}
    </div>
  );
}

export default ReceiptCounter;
